name: Daily Scraping Stocks

on:
  schedule:
    - cron: '*/5 * * * *'  # runs at 17:00 every days
  workflow_dispatch:

jobs:
  saham-scrape:
    runs-on: macos-latest
    env:
      ATLAS_URL: ${{ secrets.ATLAS_URL }}
      ATLAS_COLLECTION: ${{ secrets.ATLAS_COLLECTION }}
      ATLAS_DB: ${{ secrets.ATLAS_DB }}
    steps:
      - uses: actions/checkout@v3
      - uses: r-lib/actions/setup-r@v2
      - name: Install mongolite package
        run: Rscript -e 'install.packages("mongolite", dependencies = TRUE)'
      - name: Install rvest package
        run: Rscript -e 'install.packages("rvest", dependencies = TRUE)'
      - name: Scrape data Stocks to MongoDB 
        run: Rscript scrape_saham.R
