name: Daily Scraping Stocks

on:
  schedule:
    - cron: '0 17 */ * *'  # runs at 17:00 every days


jobs:
  saham-scrape:
    runs-on: windows-latest
    env:
      ATLAS_URL: ${{ secrets.ATLAS_URL }}
      ATLAS_COLLECTION: ${{ secrets.ATLAS_COLLECTION }}
      ATLAS_DB: ${{ secrets.ATLAS_DB }}
    steps:
      - uses: actions/checkout@v3
      - uses: r-lib/actions/setup-r@v2
      - name: Install packages
        run:
          install.packages("mongolite")
          install.packages("rvest", dependencies = TRUE)        
      - name: Scrape data Stocks to MongoDB 
        run: Rscript scrape_saham.R
